### ISSUE TITLE
🐛 [BUG]: CustomNodeProps' incorrectly extends interface 'NodeProps

### ISSUE THREAD

**Issue by kaleming** [bcakmakoglu/vue-flow#1061]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Hi, I am trying to reproduce this block of code from the documentation:

```vue.js
<script lang="ts" setup>
import type { NodeProps, NodeEventsOn } from '@vue-flow/core'

// define your events
interface CustomNodeEvents {
  click: NodeEventsOn['click']
  customEvent: (input: string) => void
}

interface CustomNodeProps extends NodeProps<any, CustomNodeEvents> {
  id: string
  events: CustomNodeEvents
}

const props = defineProps<CustomNodeProps>()

props.events.click(() => {
  console.log(`Node ${props.id} clicked`)
})

// custom events are just functions, they are not hooks which you can listen to like `click`
props.events.customEvent('custom event triggered')
</script>


```

However, I am facing this type error:

```
Interface 'CustomNodeProps' incorrectly extends interface 'NodeProps<any, CustomNodeEvents, string>'.
  Types of property 'events' are incompatible.ts(2430)
interface CustomNodeProps
```

### Expected Behavior

A working app when choose <script lang="ts" setup>

### Steps To Reproduce

1- I created a vue3 project with pinia and typescript
2- copied your pinia example (https://vueflow.dev/examples/pinia.html)
3- Add on Vue.app file a block of code presented on (Custom) Node Events section in  documentation

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'click')
    at setup (App.vue:26:14)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7236:25)
    at setupComponent (runtime-core.esm-bundler.js:7197:36)
    at mountComponent (runtime-core.esm-bundler.js:5599:7)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
    at patch (runtime-core.esm-bundler.js:5040:11)
    at render2 (runtime-core.esm-bundler.js:6332:7)
    at mount (runtime-core.esm-bundler.js:3824:13)
    at app.mount (runtime-dom.esm-bundler.js:1431:19)
```

**Comment by bcakmakoglu** [comment]
1. You don't need to re-define `click` in your custom events, it's already a default one and you're not overwriting it seemingly.
2. You don't need to re-define `emits` in the props, by doing so, you forcibly overwrite the prop from `NodeEventsOn<CustomEvents>` to your own `interface CustomNodeEvents` type. If necessary use `NodeEventsOn<CustomNodeEvents>` as the type for emits.

```vue
<script lang="ts" setup>
import type { NodeProps } from '@vue-flow/core'

// define your events
interface CustomNodeEvents {
  customEvent: (input: string) => void
}

interface CustomNodeProps extends NodeProps<any, CustomNodeEvents> {
  id: string
}

const props = defineProps<CustomNodeProps>()

props.events.click(() => {
  console.log(`Node ${props.id} clicked`)
});

props.events.customEvent('foo');
```

and you're good to go, I'll update the pinia example at some point :)
