### ISSUE TITLE
🐛 [BUG]: Fit control throws an unhandled error

### ISSUE THREAD

**Issue by binarytide** [bcakmakoglu/vue-flow#1168]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

adding Controls and clicking fit button produces an unhandled error

### Expected Behavior

expectation is that it fits nodes in view

### Steps To Reproduce

1: create a simple vue flow component and include controls
2: click fit

### Relevant log output

```shell
runtime-core.esm-bundler.js:221 Uncaught TypeError: C is not a function
    at x (vue-flow-controls.mjs:95:7)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:595:5)
```

### Anything else?

seems like the lock button also isn't doing anything but that doesn't throw anything in the console

**Comment by binarytide** [comment]
turns out I had passed fitView as a param to useVueFlow for some reason. removing that solved the issue
