### ISSUE TITLE
🐛 [BUG]: Unable to use MiniMap or Controls due to missing Panels export in Core. 

### ISSUE THREAD

**Issue by MichaelTeeuw** [bcakmakoglu/vue-flow#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When trying to use the MiniMap or Controls component, Vite throws an error: 
```
No matching export in "node_modules/@vue-flow/core/dist/vue-flow-core.mjs" for import "Panel"
```

### Expected Behavior

I expect the MiniMap or Controls component to be usable. :)

### Steps To Reproduce

In a new vue project, try the following:
```
<template>
<VueFlow :nodes="[]">
<MiniMap />
<Controls />
</VueFlow>
</template>
<script setup>
import { VueFlow  } from '@vue-flow/core'
import { MiniMap } from '@vue-flow/minimap'
import { Controls } from '@vue-flow/controls'
</script>
```

### Relevant log output

```shell
15:53:33 [vite] hmr update /resources/js/components/WorkflowEditor.vue
hmr update /resources/css/app.css
✘ [ERROR] No matching export in "node_modules/@vue-flow/core/dist/vue-flow-core.mjs" for import "Panel"

    node_modules/@vue-flow/minimap/dist/vue-flow-minimap.mjs:2:73:
      2 │ ...ctOfNodes as gn, getBoundsofRects as vn, Panel as yn, getConnectedEdges as ut } from "...
        ╵                                             ~~~~~

✘ [ERROR] No matching export in "node_modules/@vue-flow/core/dist/vue-flow-core.mjs" for import "Panel"

    node_modules/@vue-flow/controls/dist/vue-flow-controls.mjs:2:26:
      2 │ import { useVueFlow as x, Panel as F } from "@vue-flow/core";
        ╵                           ~~~~~

15:53:34 [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/@vue-flow/controls/dist/vue-flow-controls.mjs:2:26: ERROR: No matching export in "node_modules/@vue-flow/core/dist/vue-flow-core.mjs" for import "Panel"
node_modules/@vue-flow/minimap/dist/vue-flow-minimap.mjs:2:73: ERROR: No matching export in "node_modules/@vue-flow/core/dist/vue-flow-core.mjs" for import "Panel"
    at failureErrorWithLog (/Users/Michael/Code/itvs-datahub/node_modules/esbuild/lib/main.js:1574:15)
    at /Users/Michael/Code/itvs-datahub/node_modules/esbuild/lib/main.js:1032:28
    at runOnEndCallbacks (/Users/Michael/Code/itvs-datahub/node_modules/esbuild/lib/main.js:1446:61)
    at buildResponseToResult (/Users/Michael/Code/itvs-datahub/node_modules/esbuild/lib/main.js:1030:7)
    at /Users/Michael/Code/itvs-datahub/node_modules/esbuild/lib/main.js:1142:14
    at responseCallbacks.<computed> (/Users/Michael/Code/itvs-datahub/node_modules/esbuild/lib/main.js:679:9)
    at handleIncomingPacket (/Users/Michael/Code/itvs-datahub/node_modules/esbuild/lib/main.js:734:9)
    at Socket.readFromStdout (/Users/Michael/Code/itvs-datahub/node_modules/esbuild/lib/main.js:655:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
```
```


### Anything else?

Love this package. You people are awesome! <3

**Comment by bcakmakoglu** [comment]
[Please refer to the migration guide here.](https://vueflow.dev/migration/)

**Comment by bcakmakoglu** [comment]
No worries, it's not super obvious that the components only work with 1.6.0 - I should update the peer dependencies ^^
